# Oh My Zsh Settings
export ZSH="$HOME/.oh-my-zsh" # Path to OMZ config
zstyle ':omz:update' mode disabled  # disable auto updates, chezmoi handles this
ZSH_THEME="robbyrussell"

plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
    vscode)

ZSH_AUTOSUGGEST_STRATEGY=(
    completion
    history
)

source $ZSH/oh-my-zsh.sh

# Get environmental variables from ~/.env_vars if it exists (in order to keep separate env variables per computer)
if [ -f ~/.env_vars ]; then
    source ~/.env_vars
fi

# Universal Aliases / Env Vars
# set editor to nvim if present - used for sudoedit
if command -v nvim >/dev/null 2>&1; then
    export EDITOR=nvim
fi

alias gitig="touch .gitignore && echo -e '*.env\n*.DS_Store\n.idea' >> .gitignore" # Create a .gitignore file with common entries

# Linux-Specific
alias nixconf="cd ~/.config/nixos/"
alias nixbuild="sudo nixos-rebuild switch --flake ~/.config/nixos#nixos"

# Go Env Vars
if [ -d /usr/local/go ]; then
    export GOROOT=/usr/local/go
    export PATH=$PATH:$GOROOT/bin
fi

export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$PATH 
export PATH=$HOME/bin:$PATH
