#!/usr/bin/env bash

theme_path="$HOME/.config/rofi/themes/clipboard.rasi"

if ! pgrep -x rofi >/dev/null; then
    selection=$(cliphist list | rofi -dmenu -i -theme $theme_path -p "Clipboard")
    [ -n "$selection" ] && cliphist decode <<<"$selection" | wl-copy
else
    pkill -x rofi
fi
